### ISSUE TITLE
windows install folder differs

### ISSUE THREAD

**Issue by don-eng** [YoruAlptraum/no-splash-opera-gx#1]
On my computer,  opera is installed into C:\Program Files\Opera

I also removed the filter for pattern as it can search that whole directory

```
@echo off
set "directory=C:\Program Files\Opera"
for /d %%a in ("%directory%\*") do (
    if exist "%%a\opera_gx_splash.exe" (
        del "%%a\opera_gx_splash.exe"
        set "result=%%a\opera_gx_splash.exe"
    ) 
)
echo %TIME% - %result% >> "%~dp0task_monitoring.log"

@rem launch opera gx
"C:\Program Files\Opera\launcher.exe"

exit /b 0
```

**Comment by YoruAlptraum** [comment]
Thank you for your input. I ran some tests and noticed the pattern filter was actually slower than not having it and removed it from the .bat script
I'm looking into a way for the script to use a path relative to the .exe file instead of a hard coded path to avoid the issue with folder location 
I'll probably rewrite the code in powershell since batch does not seem to have a straightforward way to find the location it is being ran on from the exe wrapper

**Comment by YoruAlptraum** [comment]
I released a new update that uses the relative path of the script instead of assuming a default location for the Opera GX folder so I'm closing this issue. 
If there are any other issues feel free to let me know again.
